/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CTest */

#ifndef _Included_CTest
#define _Included_CTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CTest
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CTest_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
